catalog_name: dbw_mavencourse_e2emlops_weu_001
schema_name: sleep_efficiency
use_case_name: sleep_efficiencies
volume_whl_path: ${VOLUME_WHL_PATH}
user_dir_path: ${USER_DIR_PATH}
git_repo: marvelous-databricks-course-srues2

parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

ab_test:
  learning_rate_a: 0.02
  learning_rate_b: 0.02
  n_estimators: 1000
  max_depth_a: 6
  max_depth_b: 10

num_features:
  - age
  - sleep_duration
  - rem_sleep_percentage
  - deep_sleep_percentage
  - light_sleep_percentage
  - awakenings
  - caffeine_consumption
  - alcohol_consumption
  - exercise_frequency

cat_features:
  - gender
  - smoking_status

date_features:
  - bedtime
  - wakeup_time

target: sleep_efficiency

primary_key: ID