catalog_name: dbw_mavencourse_e2emlops_weu_001
schema_name: sleep_efficiency
use_case_name: sleep_efficiencies
volume_whl_path: ${VOLUME_WHL_PATH}
user_dir_path: ${USER_DIR_PATH}
git_repo: marvelous-databricks-course-srues2

parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

ab_test:
  learning_rate_a: 0.02
  learning_rate_b: 0.02
  n_estimators: 1000
  max_depth_a: 6
  max_depth_b: 10

num_features:
  age:
    type: integer
    constraints: 
      min: 0
      max: null
  sleep_duration:
    type: float
    constraints:
      min: 0.0
      max: null
  rem_sleep_percentage:
    type: integer
    constraints: 
      min: 0
      max: null
  deep_sleep_percentage:
    type: integer
    constraints: 
      min: 0
      max: null
  light_sleep_percentage:
    type: integer
    constraints: 
      min: 0
      max: null
  awakenings:
    type: float
    constraints:
      min: 0.0
      max: null
  caffeine_consumption:
    type: float
    constraints:
      min: 0.0
      max: null
  alcohol_consumption:
    type: float
    constraints:
      min: 0.0
      max: null
  exercise_frequency:
    type: float
    constraints:
      min: 0.0
      max: null

cat_features:
  gender:
    type: string
    allowed_values: ["Female", "Male"]
  smoking_status:
    type: string
    allowed_values:  ["Yes", "No"]

date_features:
  bedtime:
    type: timestamp
  wakeup_time:
    type: timestamp

target: sleep_efficiency

primary_key: ID